### ISSUE TITLE
Matching fails when variants are used

### ISSUE THREAD

**Issue by brendanberg** [brendanberg/L#11]
```
>> {{ (Boolean.True) -> { 't' }, (Boolean.False) -> { 'f' } }}(0 == 0)
ReferenceError: AST is not defined
    at capture (/Users/berg/Documents/projects/L/src/context.js:217:31)
    at capture (/Users/berg/Documents/projects/L/src/context.js:99:12)
    at Context.match (/Users/berg/Documents/projects/L/src/context.js:231:12)
    at Context.extend (/Users/berg/Documents/projects/L/src/context.js:27:22)
    at Record.FunctionCall.eval (/Users/berg/Documents/projects/L/src/ast/functioncall.js:47:29)
    at /Users/berg/Documents/projects/L/src/ast/evaluate.js:29:40
    at /Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4418:31
    at List.__iterate (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:2206:13)
    at List.reduce (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4413:12)
    at Record.Evaluate.eval (/Users/berg/Documents/projects/L/src/ast/evaluate.js:28:23)
```

**Comment by brendanberg** [comment]
Fixed in lucky #13
