### ISSUE TITLE
Function application chaining either breaks the stack or misapplies

### ISSUE THREAD

**Issue by brendanberg** [brendanberg/L#12]
```
>> Y :: (f) -> {
 -   (x) -> {
 -     f((y) -> { x(x)(y) })
 -   }((x) -> {
 -     f((y) -> { x(x)(y) })
 -   })
 - }
[$Y: (f) -> {
    (x) -> {
        f((y) -> {
            x(x)(y)
        })
    }((x) -> {
        f((y) -> {
            x(x)(y)
        })
    })
}]
>> fact :: (fn) -> {{
 -   (0) -> { 1 }
 -   (n) -> { n * fn(n - 1) }
 - }}
[$fact: (fn) -> {
    (0) -> {
        1
    }
    (n) -> {
        n * fn(n - 1)
    }
}]
>> Y(fact)
(n) -> {
    n * fn(n - 1)
}
>> Y(fact)(5)
RangeError: Maximum call stack size exceeded
    at List.first (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4782:19)
    at capture (/Users/berg/Documents/projects/L/src/context.js:99:39)
    at Context.match (/Users/berg/Documents/projects/L/src/context.js:231:12)
    at Context.extend (/Users/berg/Documents/projects/L/src/context.js:27:22)
    at Record.FunctionCall.eval (/Users/berg/Documents/projects/L/src/ast/functioncall.js:39:24)
    at Record.FunctionCall.eval (/Users/berg/Documents/projects/L/src/ast/functioncall.js:31:27)
    at /Users/berg/Documents/projects/L/src/ast/evaluate.js:29:40
    at /Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4418:31
    at List.__iterate (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:2206:13)
    at List.reduce (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4413:12)
```

```
>> curry :: (f)->(x)->(y)->{ f(x, y) }
[$curry: (f) -> (x) -> (y) -> {
    f(x, y)
}]
>> add :: (a, b) -> { a + b }
[$add: (a, b) -> {
    a + b
}]
>> add3 :: curry(add)(3)
[$add3: (y) -> {
    f(x, y)
}]
>> add3(2)
TypeError: Cannot read property 'apply' of undefined
    at Record.<anonymous> (/Users/berg/Documents/projects/L/src/dispatch.js:5:28)
    at Record.Invocation.eval (/Users/berg/Documents/projects/L/src/ast/invocation.js:80:17)
    at Record.InfixExpression.eval (/Users/berg/Documents/projects/L/src/ast/infixexpression.js:34:66)
    at /Users/berg/Documents/projects/L/src/ast/evaluate.js:29:40
    at /Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4418:31
    at List.__iterate (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:2206:13)
    at List.reduce (/Users/berg/Documents/projects/L/node_modules/immutable/dist/immutable.js:4413:12)
    at Record.Evaluate.eval (/Users/berg/Documents/projects/L/src/ast/evaluate.js:28:23)
    at Record.FunctionCall.eval (/Users/berg/Documents/projects/L/src/ast/functioncall.js:75:42)
    at /Users/berg/Documents/projects/L/src/ast/evaluate.js:29:40
```

**Comment by brendanberg** [comment]
Currying example is fixed in #13:

```
>> curry :: (f)->(x)->(y)->{ f(x, y) }
[$curry: (f) -> (x) -> (y) -> {
    f(x, y)
}]
>> add :: (a, b) -> { a + b }
[$add: (a, b) -> {
    a + b
}]
>> add3 :: curry(add)(3)
[$add3: (y) -> {
    f(x, y)
}]
>> add3(2)
5
```

**Comment by brendanberg** [comment]
Another wrinkle: `(fn)->(x)->{ ... }` works, while `(fn)->{{ (x)->{ ... } }}` doesn't.

```
>> fact :: (fn)->(x)->{ {{ (1)->{1}, (n)->{ n * fn(n - 1) } }}(x) }
[$fact: (fn) -> (x) -> {
    {{
        (1) -> {
            1
        }
        (n) -> {
            n * fn(n - 1)
        }
    }}(x)
}]
>> Y(fact)(1)
1
>> Y(fact)(2)
2
>> Y(fact)(10)
3628800
```

**Comment by brendanberg** [comment]
Fixed by adding match definitions to the list of allowed function bodies. See #16
